name: Közlekedés
description: Közlekedési infrastruktúra, vasút, autópálya, tömegközlekedés, útépítés
feeds:
- telex
- '444'
- hvg
- nepszava
- index
- 24hu
- hirado
- portfolio
- vg
- magyarnemzet
- mandiner
- 168hu
- hungarytoday
- budapesttimes
filter:
  pattern: (kozleked|vasut|autopalya|tomegkozleked|metro|villamos|busz|vonat|MAV|BKK|utepites|hid|repulot|infrastruktur).*
  fields:
  - title
  - summary
ranking:
  query: 'közlekedés infrastruktúra vasút fejlesztés autópálya tömegközlekedés MÁV
    BKK metró felújítás útépítés

    '
  model: paraphrase-multilingual-MiniLM-L12-v2
