name: Oktatás
description: Oktatási reform, pedagógusbérek, egyetemek, iskolák, tanársztrájk
feeds:
- telex
- '444'
- hvg
- nepszava
- index
- 24hu
- hirado
- portfolio
- vg
- magyarnemzet
- mandiner
- 168hu
- hungarytoday
- budapesttimes
filter:
  pattern: (oktatas|iskola|egyetem|tanar|pedagogus|tankotel|diakhitel|ovoda|bolcsode|felsooktatas|kozoktat|tanev|erettsegi|felvételi|ösztöndíj).*
  fields:
  - title
  - summary
ranking:
  query: 'oktatási reform pedagógus béremelés egyetem iskola tanárhiány közoktatás
    felsőoktatás diák tanév tankönyv

    '
  model: paraphrase-multilingual-MiniLM-L12-v2
  negative_queries:
  - sport
output:
  filename: oktatas_filtered.html
  filename_ranked: oktatas_ranked.html
  archive: true
