name: Szociálpolitika
description: Szociális ellátás, lakhatás, családpolitika, szegénység, roma integráció
feeds:
- telex
- '444'
- hvg
- nepszava
- index
- 24hu
- hirado
- portfolio
- vg
- magyarnemzet
- mandiner
- 168hu
- hungarytoday
- budapesttimes
filter:
  pattern: (szocialis|lakhat|lakas(tamogatas|hitel|piac)|hajlektalan|szegenyseg|segely|szociális.?ellatas|gyermekvedel|csaladtamogat|roma|eselyegyenloseg|idos|gondoz|fogyatek).*
  fields:
  - title
  - summary
ranking:
  query: 'szociálpolitika lakhatás lakástámogatás hajléktalanság szegénység családtámogatás
    gyermekvédelem esélyegyenlőség idősek gondozás

    '
  model: paraphrase-multilingual-MiniLM-L12-v2
